- name: "Installing {{ item.name }}"
  apt:
     name: "{{ item.name }}"
     state: "{{ item.state }}"
     update_cache: "{{ item.cacheUpdate }}"
     install_recommends: "{{ item.installDependency }}"
  with_items: 
    - "{{ packages }}" 
