---
# defaults file for prerequisites
packages:
  - name: gnupg
    havingDeBFile: False
    debPath: ''    
    state: present
    cacheUpdate: True
    installDependency: True
  - name: unzip
    havingDeBFile: False
    debPath: ''    
    state: present
    cacheUpdate: True
    installDependency: True
  - name: git
    havingDeBFile: False
    debPath: ''    
    state: present
    cacheUpdate: True
    installDependency: True